# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Javascript company meetings
email: 
description:
baseurl: "/javascript-company-meeting" # the subpath of your site, e.g. /blog
url: "http://mathiastim.github.io" # the base hostname & protocol for your site
twitter_username: mwaysolutions
github_username:  mwaylabs

# Build settings
markdown: kramdown
